openapi: "3.0.0"
info:
  version: 1.0.0
  title: KVStore API
  description: API for a distributed key-value store
paths:
  /ping:
    get:
      operationId: pingServer
      x-go-name: PingServer
      summary: Health check endpoint
      responses:
        "200":
          description: ping response
          x-go-name: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pong"
        default:
          description: Unexpected error
          x-go-name: Error
          content:
            application/json:
              schema:
                $ref: "../common/api.yaml#/components/schemas/ErrorResponse"
  /kv/{key}:
    get:
      operationId: getValue
      x-go-name: GetValue
      summary: Get a value by key
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
          description: Key to retrieve
          x-go-name: Key
      responses:
        "200":
          description: Value retrieved successfully
          x-go-name: Success
          content:
            application/json:
              schema:
                $ref: "../common/api.yaml#/components/schemas/KeyValueResponse"
        "404":
          description: Key not found
          x-go-name: NotFound
          content:
            application/json:
              schema:
                $ref: "../common/api.yaml#/components/schemas/ErrorResponse"
        default:
          description: Unexpected error
          x-go-name: Error
          content:
            application/json:
              schema:
                $ref: "../common/api.yaml#/components/schemas/ErrorResponse"
    put:
      operationId: setValue
      x-go-name: SetValue
      summary: Set a key-value pair
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
          description: Key to set
          x-go-name: Key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../common/api.yaml#/components/schemas/SetValueRequest"
      responses:
        "200":
          description: Value set successfully
          x-go-name: Success
          content:
            application/json:
              schema:
                $ref: "../common/api.yaml#/components/schemas/KeyValuePair"
        "400":
          description: Invalid request
          x-go-name: BadRequest
          content:
            application/json:
              schema:
                $ref: "../common/api.yaml#/components/schemas/ErrorResponse"
        default:
          description: Unexpected error
          x-go-name: Error
          content:
            application/json:
              schema:
                $ref: "../common/api.yaml#/components/schemas/ErrorResponse"
    delete:
      operationId: deleteKey
      x-go-name: DeleteKey
      summary: Delete a key-value pair
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
          description: Key to delete
          x-go-name: Key
      responses:
        "200":
          description: Key deleted successfully
          x-go-name: Success
          content:
            application/json:
              schema:
                $ref: "../common/api.yaml#/components/schemas/DeleteResponse"
        "404":
          description: Key not found
          x-go-name: NotFound
          content:
            application/json:
              schema:
                $ref: "../common/api.yaml#/components/schemas/ErrorResponse"
        default:
          description: Unexpected error
          x-go-name: Error
          content:
            application/json:
              schema:
                $ref: "../common/api.yaml#/components/schemas/ErrorResponse"
components:
  schemas:
    Pong:
      type: object
      required:
        - ping
      properties:
        ping:
          type: string
          example: pong
          x-go-name: Ping
