BINARY_NAME=kvstore
GO_FILES=main.go

# Get version from git tag if available, otherwise use commit hash
VERSION=$(shell git describe --tags 2>/dev/null || git rev-parse --short HEAD)

.PHONY: build clean generate

build:
	@echo "Building $(BINARY_NAME) with version $(VERSION)..."
	go build -ldflags "-X config.Version=$(VERSION)" -o $(BINARY_NAME) $(GO_FILES)
	@echo "Build complete: $(BINARY_NAME)"

clean:
	find . -type f -name "*.go"  -exec grep -qE "// Code generated by .*\. DO NOT EDIT\." {} \; -delete

generate:
	@go get -tool github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
	@go generate ./...

all: build

