openapi: "3.0.0"
info:
  version: 1.0.0
  title: Database API Server
paths:
  /state:
    get:
      summary: Get the current state of the database node
      description: Returns the current status and partition ID of the database node
      responses:
        "200":
          description: State information retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NodeState"
components:
  schemas:
    NodeState:
      type: object
      required:
        - status
      properties:
        status:
          $ref: "../common/api.yaml#/components/schemas/Status"
        partitionId:
          type: string
          description: ID of the partition this node belongs to
          example: "partition-1"
