openapi: "3.0.0"
info:
  version: 1.0.0
  title: Minimal ping API server
paths:
  /state:
    get:
      responses:
        "200":
          description: Retrieved State Successfully
          content:
            application/json:
              schema:
                $ref: "../common/api.yaml#/components/schemas/State"
  /nodes/register:
    post:
      summary: Register a new node with the controller
      description: Endpoint for nodes to register themselves when starting up
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NodeRegistration"
      responses:
        "201":
          description: Node registered successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NodeRegistrationResponse"
        "400":
          description: Invalid request
        "409":
          description: Node already registered
components:
  schemas:
    NodeRegistration:
      type: object
      required:
        - address
      properties:
        address:
          type: string
          description: Network address of the node (host:port)
          example: "192.168.1.10:8080"
    NodeRegistrationResponse:
      type: object
      required:
        - id
        - status
      properties:
        id:
          type: string
          format: uuid
          description: Assigned unique identifier for the node
        status:
          $ref: "../common/api.yaml#/components/schemas/Status"
