openapi: "3.0.0"
info:
  version: 1.0.0
  title: Loadbalancer API
paths:
  /state:
    put:
      operationId: setState
      summary: Sets the loadbalancer state
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../common/api.yaml#/components/schemas/State"
      responses:
        "200":
          description: State successfully updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StateResponse"
  /ping:
    get:
      responses:
        "200":
          description: ping response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pong"
components:
  schemas:
    Pong:
      type: object
      required:
        - ping
      properties:
        ping:
          type: string
          example: pong
    StateResponse:
      type: object
      properties:
        message:
          type: string
          description: Optional message providing additional information
          example: "State updated successfully"
