name: "Check Generated"
on:
  push:
    branches:
      - "*"
  pull_request:
permissions:
  contents: read
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.24.2"
          cache: true
      - name: Run Generate
        run: make generate
      - name: Check for uncommitted changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Error: There are uncommitted changes after running 'go generate'."
            echo "This usually means that generated files are out of date."
            echo "Please run 'go generate ./...' locally and commit the changes."
            git status
            git diff
            exit 1
          fi
